cleanall:
	@rm -f	*.o *.mod *.pyc *.dat *.out *.info *.used           \
	   *wavelength_micron.inp dustopac.inp dust_density.inp     \
	   dust_density.uinp *.uout *.udat                          \
	   amr_grid.inp stars.inp radmc3d.inp image_script.pro      \
	   radmc3d Makefile~ *.pro~ README*~ *.f90~ *.inp~ *.py~    \
	   dustkapscatmat_pyrmg70.inp dustkappa_pyrmg70.inp
	@echo Directory cleaned to basic
