cleanmodel:
	@rm -f	*.dat *.out *.info *.used                           \
	   wavelength_micron.inp dustopac.inp dust_density.inp      \
	   dust_density.uinp *.uout *.udat numberdens_*inp          \
	   amr_grid.inp stars.inp radmc3d.inp gas_temperature.*inp  \
	   gas_velocity.inp lines.inp microturbulence.*
	@echo All .out files and most .inp files removed.

cleanall:
	@rm -f	*.o *.mod *.pyc *.dat *.out *.info *.used           \
	   wavelength_micron.inp dustopac.inp dust_density.inp      \
	   dust_density.uinp *.uout *.udat numberdens_*inp          \
	   amr_grid.inp stars.inp radmc3d.inp image_script.pro      \
	   radmc3d Makefile~ *.pro~ README*~ *.f90~ *.inp~          \
	   gas_velocity.inp lines.inp  microturbulence.*            \
	   gas_temperature.*inp *.py~ 
	@echo Directory cleaned to basic
