cleanall:
	@rm -f	*.o *.mod *.dat *.out *.info *.used                 \
	   frequency.inp dustkappa_*.inp dust.inp                   \
	   makedust molecule_*.inp *~
	@echo Directory cleaned to basic
