cleanmodel:
	@rm -f	*.o *.mod *.dat *.out *.info *.used                 \
	   *wavelength_micron.inp dustopac.inp dust_density.inp     \
	   dust_density.uinp *.uout *.udat numberdens_*.*inp        \
	   amr_grid.inp stars.inp radmc3d.inp                       \
	   microturbulence.*inp lines.inp gas_velocity.*inp
	@echo All .o, .mod, .out files and most .inp files removed.

cleanall:
	@rm -f	*.o *.mod *.pyc *.dat *.out *.info *.used           \
	   *wavelength_micron.inp dustopac.inp dust_density.inp     \
	   dust_density.uinp *.uout *.udat numberdens_*.*inp        \
	   amr_grid.inp stars.inp radmc3d.inp image_script.pro      \
           microturbulence.*inp lines.inp gas_velocity.*inp         \
	   radmc3d Makefile~ *.pro~ README*~ *.f90~ *.inp~ *.py~
	@echo Directory cleaned to basic
